[project]
name = "xaal.dummy"
version = "0.1"
description = "xAAL dummy devices"
readme = "README.rst"
authors = [ { name = "Jerome Kerdreux", email = "Jerome.Kerdreux@imt-atlantique.fr" } ]
license = { text = "GPL License"}
classifiers = ["Programming Language :: Python",
"Topic :: Software Development :: Libraries :: Python Modules"]
keywords = ["xaal"]
dependencies = ["xaal.lib"]


[tool.setuptools.packages.find]
include = ["xaal.dummy"]
