[project]
name = "xlpkg"
version = "1.0.0.33"
authors = [
  { name="xiaolong", email="longx888@126.com" },
]
description = "xiaolong public package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
#requires = ["setuptools>=60.0"]
#build-backend = "setuptools.build_meta"
requires = ["hatchling"]
build-backend = "hatchling.build"


[project.urls]
Homepage = "https://github.com/dellcell/xlpkg"
Issues = "https://github.com/dellcell/xlpkg/issues"
