[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "exo_horoscope"
version = "0.0.17"

dependencies = [
    "numpy>=1.24.0",
    "datetime",
    "geopy>=2.4.1",
    "astropy>=5.3",
    "astroquery>=0.4.7"
]

[tool.setuptools]
packages = ["exo_horoscope"]
include-package-data = true

[tool.setuptools.package-data]
exo_horoscope = ["confirmed_exoplantes_table.ecsv"]

