[build-system]
requires = ["setuptools>=65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shake-that-assurance"
version = "0.0.6"
description = "Python api wrapper for Unified Assurance"
readme = "README.md"
authors = [{ name = "Brian Lee", email = "brian.baligad.lee@zayo.com" }]
license = { file = "LICENSE" }
dependencies = [
    'build>=1.2.1',
    'requests>=2.31.0',
    'pytest>=8.1.1',
]
requires-python = ">=3.11.6"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: System :: Monitoring",
]

[project.urls]
Homepage = "https://github.com/bleetube/shake-that-assurance"

#[project.scripts]
#ua-migrate-zone = "migrate.migrate:migrate_zone"