[project]
name = "accidental-vulnerability"
version = "2.0.6"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "Accidental inherit"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi<=0.5",
    "safety>=3.2.4",
    "uvicorn>=0.30.1",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
