[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cgo_mkto_api_aastudillocgo"
version = "0.1.28"
authors = [
  { name="Angel Xavier Astudillo Aguilar", email="aastudillo@citizengo.net" },
]
description = "A package to use the bulk API of Marketo, designed for Citizengo"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://citizengo.org/en-us"