[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "exo_horoscope"
version = "0.0.11"

[tool.setuptools]
packages = ["exo_horoscope"]
include-package-data = true

[tool.setuptools.package-data]
exo_horoscope = ["confirmed_exoplantes_table.ecsv"]

dependencies = [
    "numpy",
    "datetime",
    "geopy",
    "astropy",
    "astroquery"
]