[tool.poetry]
name = "mlable"
version = "0.6.9"
description = "Tensorflow libs: layers, metrics, ops, etc."
authors = ["apehex <apehex@protonmail.com>"]
readme = ".github/README.md"
packages = [{include = "mlable"}]

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
tensorflow = ">=2.15"

[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
