Download_Options:
  block_download_sub_folders: false
  disable_download_attempt_limit: false
  disable_file_timestamps: false
  include_album_id_in_folder_name: false
  include_thread_id_in_folder_name: false
  remove_domains_from_folder_names: false
  remove_generated_id_from_filenames: false
  scrape_single_forum_post: false
  separate_posts: false
  skip_download_mark_completed: false
File_Size_Limits:
  maximum_image_size: 0
  maximum_other_size: 0
  maximum_video_size: 0
  minimum_image_size: 0
  minimum_other_size: 0
  minimum_video_size: 0
Files:
  download_folder: Downloads/Cyberdrop-DL Downloads
  input_file: AppData/Configs/Default/URLs.txt
Ignore_Options:
  exclude_audio: false
  exclude_images: false
  exclude_other: false
  exclude_videos: true
  ignore_coomer_ads: true
  only_hosts: []
  skip_hosts: []
Logs:
  download_error_urls_filename: Download_Error_URLs.csv
  last_forum_post_filename: Last_Scraped_Forum_Posts.txt
  log_folder: AppData/Configs/Default/Logs
  main_log_filename: downloader.log
  scrape_error_urls_filename: Scrape_Error_URLs.csv
  unsupported_urls_filename: Unsupported_URLs.txt
Runtime_Options:
  delete_partial_files: false
  ignore_history: false
  log_level: 10
  send_unsupported_to_jdownloader: false
  skip_check_for_empty_folders: false
  skip_check_for_partial_files: false
  update_last_forum_post: false
Sorting:
  sort_downloads: false
  sort_folder: Downloads/Cyberdrop-DL Sorted Downloads
  sort_incremementer_format: ' ({i})'
  sorted_audio: '{sort_dir}/{base_dir}/Audio/{filename}{ext}'
  sorted_image: '{sort_dir}/{base_dir}/Images/{filename}{ext}'
  sorted_other: '{sort_dir}/{base_dir}/Other/{filename}{ext}'
  sorted_video: '{sort_dir}/{base_dir}/Videos/{filename}{ext}'
