[project]
name = "Python-piSPM"
version = "7.10.0.2"
description = "Python piSPM is a Python wrapper for Pickering Switch Path Manager."
readme = "README.md"
license = {file = "LICENSE.txt"}
authors = [
    {name = "Pickering Interfaces", email = "support@pickeringtest.com"}
]
dependencies = [
    "future"
]

[project.urls]
homepage = "https://www.pickeringtest.com/"