[project]
name = "steam-openid"
version = "1.0.3"
authors = [
  { name="imtaas" }
]
description = "A simple package for integrating Steam OpenID authentication in applications."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/imtaas/steam-openid"
Issues = "https://github.com/imtaas/steam-openid/issues"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
