[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ndx-patterned-ogen"
version = "0.1.0"
authors = [
    { name="Alessandra Trapani", email="alessandra.trapani@catalystneuro.com" },
]
description = "patterned (holographic) optogenetic extension to NWB standard"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "BSD-3"}
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
]
keywords = [
    'NeurodataWithoutBorders',
    'NWB',
    'nwb-extension',
    'ndx-extension',
]
dependencies = [
    "pynwb>=2.5.0",
    "hdmf>=3.10.0",
    "numpy<2.0",  # TODO: remove when HDMF supports
]

# TODO: add URLs before release
# [project.urls]
# "Homepage" = "https://github.com/organization/package"
# "Documentation" = "https://package.readthedocs.io/"
# "Bug Tracker" = "https://github.com/organization/package/issues"
# "Discussions" = "https://github.com/organization/package/discussions"
# "Changelog" = "https://github.com/organization/package/blob/main/CHANGELOG.md"

[tool.hatch.build]
include = [
    "src/pynwb",
    "spec/ndx-patterned-ogen.extensions.yaml",
    "spec/ndx-patterned-ogen.namespace.yaml",
]
exclude = [
    "src/pynwb/tests",
]

[tool.hatch.build.targets.wheel]
packages = [
    "src/pynwb/ndx_patterned_ogen",
    "spec"
]

[tool.hatch.build.targets.wheel.sources]
"spec" = "ndx_patterned_ogen/spec"

[tool.hatch.build.targets.sdist]
include = [
    "src/pynwb",
    "spec/ndx-patterned-ogen.extensions.yaml",
    "spec/ndx-patterned-ogen.namespace.yaml",
    "docs",
]
exclude = []

[tool.pytest.ini_options]
addopts = "--cov --cov-report html"

[tool.codespell]
skip = "htmlcov,.git,.mypy_cache,.pytest_cache,.coverage,*.pdf,*.svg,venvs,.tox,hdmf-common-schema,./docs/_build/*,*.ipynb"

[tool.coverage.run]
branch = true
source = ["src/pynwb"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@abstract"
]

[tool.black]
line-length = 120
preview = true
exclude = ".git|.mypy_cache|.tox|.venv|venv|.ipynb_checkpoints|_build/|dist/|__pypackages__|.ipynb|docs/"

[tool.ruff]
select = ["E", "F", "T100", "T201", "T203"]
exclude = [
  ".git",
  ".tox",
  "__pycache__",
  "build/",
  "dist/",
]
line-length = 120

[tool.ruff.per-file-ignores]
"src/spec/create_extension_spec.py" = ["T201"]
"src/pynwb/ndx_patterned_ogen/__init__.py" = ["E402"]  # Need to do global imports in this file after spec registration function calls

[tool.ruff.mccabe]
max-complexity = 17
