[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aimmocore-db"
version = "0.1.19"
description = "Database setup for Aimmocore"
readme = "README.md"
authors = [{ name = "Aimmo", email = "aimmoml@aimmo.co.kr" }]
requires-python = ">=3.8"
dependencies = ["loguru"]
