[project]
name = "hc_add"
version = "0.2.4"
description = "Default template for PDM package"
authors = [
    {name = "NishNovae", email = "raecrowned@gmail.com"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

#[project.scripts]
#hc_add = "hc_add.hc_add:add"

[tool.pdm]
distribution = true

[project.urls]
Homepage = "https://github.com/NishNovae/hc_calculation"
Issues = "https://github.com/NishNovae/hc_calculation/issues"
