[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/steam-api-zestx5"]

[project]
name = "steam_api_zestx5"
dependencies = [
"python-dotenv>=1.0.1",
"requests>=2.32.3",
]
version = "0.0.4"
authors = [
  { name="Ilya Buyankov", email="buyankov.ilya@gmail.com" },
]
description = "A small api wrapper"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/zestx5/steamapi"