[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "myerson"
dynamic = ["version", "description"]
authors = [
  { name="Samuel K. R. Homberg", email="samuel.homberg@uni-muenster.de" },
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'tqdm', 
  'torch >= 2.0.1, < 3',
  'numpy >= 1.25, < 2',
  'torch_geometric >= 2.3.1, < 3',
  'networkx >= 3.1',
]

[project.optional-dependencies]
docs = [
    "sphinx_rtd_theme",
    "sphinx",
]
test = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[project.urls]
Source = "https://github.com/kochgroup/myerson"
Documentation = "https://myerson.readthedocs.io/en/latest/"