[tool.poetry]
name = "pyo2"
version = "0.1.3"
description = "A lightweight method to call Rust code from Python"
license = "MIT"
authors = ["david-why <david_why@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
