[tool.poetry]
name = "eimantas_data_transformations"
version = "0.1.0"
description = "A Python library for data transformations"
authors = ["Eimantas Venslovas"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
