[project]
name = "xaal.legacytools"
version = "0.1"
description = "xAAL devices tools"
readme = "README.rst"
authors = [ { name = "Jerome Kerdreux", email = "Jerome.Kerdreux@imt-atlantique.fr" } ]
license = { text = "GPL License"}
classifiers = ["Programming Language :: Python",
"Topic :: Software Development :: Libraries :: Python Modules"]
keywords = ["xaal", "tools"]
dependencies = ["xaal.lib"]

[project.scripts]
xaal-isalive-legacy = "xaal.legacytools.isalive:main"
xaal-info-legacy = "xaal.legacytools.info:main"
xaal-dumper-legacy = "xaal.legacytools.dumper:main"
xaal-tail-legacy = "xaal.legacytools.tail:main"
xaal-walker-legacy = "xaal.legacytools.walker:main"
xaal-keygen-legacy = "xaal.legacytools.keygen:main"
xaal-log-legacy = "xaal.legacytools.log:main"
xaal-querydb-legacy = "xaal.legacytools.querydb:main"
xaal-pkgrun-legacy = "xaal.legacytools.pkgrun:main"
xaal-uuidgen-legacy = "xaal.legacytools.uuidgen:main"
xaal-inspector-legacy = "xaal.legacytools.inspector:main"

[tool.setuptools.packages.find]
include = ["xaal.legacytools"]
