[tool.poetry]
authors     = ["9FS <pray4spam@googlemail.com>"]
description = ""
license     = "MIT"
name        = "kfslog"
packages    = [{ include = "kfslog" }]
readme      = "readme.typ"
repository  = "https://github.com/9-FS/kfslog"
version     = "3.0.0"

[tool.poetry.dependencies]
colorama = { version = "^0.4.6", optional = true }
kfsfstr  = "^2.0.0"
python   = "^3.12.0"
result   = "^0.16.0"

[tool.poetry.group.dev.dependencies]
hypothesis = "^6.0.0"
pytest     = "^8.0.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires      = ["poetry-core"]
