[project]
name = "haram_sum"
version = "0.1.4"
description = "Default template for PDM package"
authors = [
    {name = "HaramSs", email = "haram8274@gmail.com"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
haram_sum = 'haram_sum.sum:sum'

[tool.pdm]
distribution = true
