[project]
name = "pretty_print_dmeurer"
version = "1.2.1"
authors = [
	{ name="Dominik Meurer", email="dom.meurer@gmx.de" },
]
description = "Makes the ANSI codes easy to use"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/DMeurer/pretty_print_dmeurer"
Issues = "https://github.com/DMeurer/pretty_print_dmeurer/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
