[build-system]
requires = ["setuptools>=65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "snow-way-out"
version = "0.0.2"
description = ""
readme = "README.md"
authors = [{ name = "Brian Lee", email = "brian.baligad.lee@zayo.com" }]
license = { file = "LICENSE" }
dependencies = [
    'build>=1.0.0',
    'requests>=2.0.0',
    'pytest>=8.0.0',
]
requires-python = ">=3.11.6"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: System :: Monitoring",
]

[project.urls]
Homepage = "https://github.com/bleetube/snow-way-out"

# https://setuptools.pypa.io/en/latest/userguide/entry_point.html
# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
#[project.scripts]
#runproject = "project.main:main"