[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "moretypeops"
version = "1.1b1"
authors = [
  { name="Nguyen Minh Khoi", email="khoi.nguyenminh100912@gmail.com" },
]
description = "More useful functions for operators when working with data types"
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/moretypeops"
Issues = "https://github.com/pypa/moretypeops/issues"