[tool.poetry]
name = "bbb-client"
version = "0.2.0a2"
description = "Client library and CLI to interact with the BBB API"
authors = [
    "Tanguy Le Carrour <tlecarrour@easter-eggs.com>",
    "Lo√Øc Dachary <ldachary@easter-eggs.com>",
]
license = "GPL-3.0-or-later"

exclude = ["bbb_client/**/*_spec.py", "bbb_client/**/*_test.py", "bbb_client/conftest.py"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.7"
requests = "^2.31.0"
untangle = "^1.2.1"

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
invoke = "^2.2.0"
isort = "^5.12.0"

[tool.poetry.group.test.dependencies]
flake8 = "^6.1.0"
mamba = "^0.11.3"
mypy = "^1.7.0"
robber = "^1.1.5"
types-setuptools = "^68.2.0.1"
types-requests = "^2.31.0.10"
types-mock = "^5.1.0.2"
responses = "^0.25.3"

[tool.poetry.scripts]
bbb = 'bbb_client.entry_points:cli'

[tool.isort]
profile = "black"
multi_line_output = 3

[[tool.mypy.overrides]]
module = [
    "mamba.*",
    "robber.*",
    "untangle.*",
]
ignore_missing_imports = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
