[build-system]
requires = ["setuptools>=42", "wheel", "pytest"]
build-backend = "setuptools.build_meta"

[project]
name = "parasplit"
version = "1.1.1"
description = "An Hi-C tool for cutting sequences using specified enzymes"
authors = [
    { name = "Bertache Djenadi", email = "samir.bertache.djenadi@gmail.com" }
]
license = { text = "AGPLv3" }
readme = { file = "README.md", content-type = "text/markdown" }
keywords = ["Hi-C", "HiC", "bioinformatics", "cutsite"]
dependencies = [
    "biopython==1.83"
]

[project.scripts]
parasplit = "parasplit.main:main_cli"

[tool.setuptools]
packages = ["parasplit"]

[tool.pytest.ini_options]
testpaths = ["test"]

