name: Continuous Integration Workflow ğŸ‘¾

# Controls when the action will run. We only want that this action to happens when
# we open a pull request that points to main
on:
  pull_request:
    branches:
      - "main"

# ----------------------------------- #
#          DEFINE THE JOBS            #
# ----------------------------------- #

jobs:
  rust_ci:
    runs-on: ubuntu-latest
    name: Run Rust CI ğŸ¦€
    steps:
      - uses: ricardoleal20/pymath_compute/.github/actions/rust_ci@ricardo/AddSolverTests

  python_ci:
    runs-on: ubuntu-latest
    name: Run Python CI ğŸ
    steps:
      - uses: ricardoleal20/pymath_compute/.github/actions/python_ci@ricardo/AddSolverTests

  tests_ci:
    runs-on: ubuntu-latest
    name: Run tests ğŸ§ª
    steps:
      - uses: ricardoleal20/pymath_compute/.github/actions/tests_ci@ricardo/AddSolverTests
