[build-system]
requires = ["setuptools >= 62.6"]
build-backend = "setuptools.build_meta"

[project]
name = "chainplotter"
version = "0.0.1"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools]
packages = ["chainplotter"]

[tool.setuptools.package-dir]
"package_name" = "./chainplotter/cosmosis_getdist.py"